# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa6b7e12beb077ec447cbf2b0af18682ae2a998225c4f45b75974f4f5306ebbb780ce4441c10ffb6789d65020431257d1feb5cc0695623ab669db802794b65d3

test:
  secret_key_base: 3c5656d427f81245ff56c0bbc5fb217027550edf897b3c9ed8b7eaf98bc471733493a34487f9d34b72ab2fbde0a26494f59bbcc6225cc01fb9eeaa770cfb083d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
